name: Gradle CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create NDK path
        run: sudo mkdir -p /usr/local/lib/android/sdk/ndk && sudo chmod 777 /usr/local/lib/android/sdk/ndk
      - name: Cache NDKs
        id: cache-ndk
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/android/sdk/ndk
          key: ${{ runner.os }}-ndk-21.0.6113669-21.1.6352462
      - name: Install NDK 21.0.6113669
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Install NDK 21.1.6352462
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.1.6352462" --sdk_root=${ANDROID_SDK_ROOT}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleFullDebug
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
